# -*- coding: utf-8 -*-
"""Data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nocX_qiqQERZ7LNlKgl8ESZxfltSPKSL
"""

import os
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Create the mandatory input folder structure
os.makedirs("data/raw", exist_ok=True)

print("Generating synthetic datasets for Day 2 tasks...")

# Configuration constants
num_funds = 40
start_date = datetime(2025, 1, 1)
end_date = datetime(2025, 3, 31)
date_range = [start_date + timedelta(days=x) for x in range((end_date-start_date).days + 1)]

# Mock baseline fund codes
amfi_codes = [100000 + i for i in range(num_funds)]
states = ['MH', 'KA', 'DL', 'TN', 'KA', 'GJ', 'WB', 'TS']

# 1. Create Mock: nav_history.csv
nav_rows = []
for code in amfi_codes:
    base_nav = np.random.uniform(10, 150)
    for dt in date_range:
        # Introduce a few random missing rows to test holiday/weekend ffill() rules
        if np.random.rand() > 0.15:
            base_nav += np.random.uniform(-1, 1) # random walk
            nav_rows.append({
                'amfi_code': code,
                'date': dt.strftime('%Y-%m-%d'),
                'nav': round(max(base_nav, 5.0), 4) # ensure mostly valid positive bounds
            })

nav_df = pd.DataFrame(nav_rows)
# Force a few explicit duplicates and anomalies to validate sorting/cleaning drops
nav_df = pd.concat([nav_df, nav_df.sample(frac=0.02)])
nav_df.to_csv("data/raw/nav_history.csv", index=False)


# 2. Create Mock: investor_transactions.csv
tx_count = 1200
tx_rows = []
for tx_id in range(1, tx_count + 1):
    random_dt = np.random.choice(date_range)
    tx_type = np.random.choice(['SIP', 'Sip', 'Lump sum', 'Purchase', 'Redemption', 'redemption'])
    kyc_var = np.random.choice(['Verified', 'Pending', 'Failed', 'Y', 'N'])

    # Intentionally leak NaN values into investor_id to challenge the IntCastingNaNError handler
    inv_id = np.nan if np.random.rand() > 0.95 else int(10000 + np.random.randint(1, 200))

    tx_rows.append({
        'transaction_id': tx_id,
        'investor_id': inv_id,
        'amfi_code': np.random.choice(amfi_codes),
        'transaction_date': random_dt.strftime('%d-%m-%Y'), # Mix date formatting rules
        'transaction_type': tx_type,
        'amount': round(np.random.uniform(-500, 100000), 2), # Introduce invalid negative checks
        'units': round(np.random.uniform(0.1, 500), 3),
        'state': np.random.choice(states),
        'kyc_status': kyc_var
    })

tx_df = pd.DataFrame(tx_rows)
tx_df.to_csv("data/raw/investor_transactions.csv", index=False)


# 3. Create Mock: scheme_performance.csv
perf_rows = []
for code in amfi_codes:
    # Intentionally inject bad corrupted non-numeric string data to enforce numeric validation routine
    ret_1y = "CORRUPTED" if np.random.rand() > 0.95 else round(np.random.uniform(5.0, 35.0), 2)

    perf_rows.append({
        'amfi_code': code,
        'expense_ratio': round(np.random.uniform(0.05, 3.0), 2), # Enforces regulatory range filter rules
        'return_1y': ret_1y,
        'return_3y': round(np.random.uniform(8.0, 25.0), 2),
        'return_5y': round(np.random.uniform(10.0, 22.0), 2)
    })

perf_df = pd.DataFrame(perf_rows)
perf_df.to_csv("data/raw/scheme_performance.csv", index=False)

print("✓ Done! Files generated inside 'data/raw/'.")
print("You can now safely run your cleaning scripts, schema creation, and analytics engine targets.")

import os
import pandas as pd
import numpy as np

# Create output directory
os.makedirs("data/processed", exist_ok=True)
print("Starting Data Cleaning Pipeline...")

# --- 1. CLEAN NAV HISTORY ---
print("Processing nav_history.csv...")
nav_df = pd.read_csv("data/raw/nav_history.csv")

# Parse dates, drop explicit duplicates, and sort
nav_df['date'] = pd.to_datetime(nav_df['date'])
nav_df = nav_df.drop_duplicates().sort_values(by=['amfi_code', 'date'])

# Forward-fill gaps (weekends/holidays) per fund group
nav_df = nav_df.groupby('amfi_code', as_index=False).apply(
    lambda x: x.set_index('date').resample('D').ffill().reset_index()
).reset_index(drop=True)

# Validate positive bounds
nav_df = nav_df[nav_df['nav'] > 0]
nav_df.to_csv("data/processed/nav_history_clean.csv", index=False)


# --- 2. CLEAN INVESTOR TRANSACTIONS ---
print("Processing investor_transactions.csv...")
tx_df = pd.read_csv("data/raw/investor_transactions.csv")

# Standardize messy string variants into specific clean categories
tx_df['transaction_type'] = tx_df['transaction_type'].str.strip().str.upper()
tx_df['transaction_type'] = tx_df['transaction_type'].replace({
    'SIP': 'SIP', 'LUMP SUM': 'LUMPSUM', 'PURCHASE': 'LUMPSUM', 'REDEMPTION': 'REDEMPTION'
})

# Fix mixed date formats dynamically
tx_df['transaction_date'] = pd.to_datetime(tx_df['transaction_date'], format='mixed')

# Safe Int casting for missing IDs (the exact fix for IntCastingNaNError)
tx_df['investor_id'] = tx_df['investor_id'].astype('Int64')

# Validate financial sanity (amount > 0)
tx_df = tx_df[tx_df['amount'] > 0]
tx_df.to_csv("data/processed/investor_transactions_clean.csv", index=False)


# --- 3. CLEAN SCHEME PERFORMANCE ---
print("Processing scheme_performance.csv...")
perf_df = pd.read_csv("data/raw/scheme_performance.csv")

# Force strings to numeric, turn corrupt strings into NaN, fill with the column median
perf_df['return_1y'] = pd.to_numeric(perf_df['return_1y'], errors='coerce')
perf_df['return_1y'] = perf_df['return_1y'].fillna(perf_df['return_1y'].median())

# Enforce regulatory upper limits on expense ratios
perf_df = perf_df[(perf_df['expense_ratio'] >= 0.1) & (perf_df['expense_ratio'] <= 2.5)]
perf_df.to_csv("data/processed/scheme_performance_clean.csv", index=False)

print("✓ All files successfully cleaned and saved inside 'data/processed/'!")

from sqlalchemy import create_engine, text

# Initialize SQLite Database Engine connection
engine = create_engine("sqlite:///bluestock_mf.db")

print("Building Star Schema layouts...")
with engine.connect() as conn:
    # Drop existing tables if running multiple times
    conn.execute(text("DROP TABLE IF EXISTS fact_transactions;"))
    conn.execute(text("DROP TABLE IF EXISTS fact_performance;"))
    conn.execute(text("DROP TABLE IF EXISTS fact_nav;"))
    conn.execute(text("DROP TABLE IF EXISTS dim_fund;"))

    # 1. Dimension Table: Funds
    conn.execute(text("""
        CREATE TABLE dim_fund (
            amfi_code INTEGER PRIMARY KEY,
            fund_name TEXT DEFAULT 'Bluestock Mutual Fund Scheme'
        );
    """))

    # 2. Fact Table: Historical NAV Trackers
    conn.execute(text("""
        CREATE TABLE fact_nav (
            amfi_code INTEGER,
            date TEXT,
            nav REAL,
            PRIMARY KEY (amfi_code, date),
            FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code)
        );
    """))

    # 3. Fact Table: Investor Transactions Ledger
    conn.execute(text("""
        CREATE TABLE fact_transactions (
            transaction_id INTEGER PRIMARY KEY,
            investor_id INTEGER,
            amfi_code INTEGER,
            transaction_date TEXT,
            transaction_type TEXT,
            amount REAL,
            units REAL,
            state TEXT,
            kyc_status TEXT,
            FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code)
        );
    """))

    # 4. Fact Table: Performance Metric Breakdowns
    conn.execute(text("""
        CREATE TABLE fact_performance (
            amfi_code INTEGER PRIMARY KEY,
            expense_ratio REAL,
            return_1y REAL,
            return_3y REAL,
            return_5y REAL,
            FOREIGN KEY (amfi_code) REFERENCES dim_fund(amfi_code)
        );
    """))
    print("✓ Schema layout successfully created.")

# --- LOAD CLEAN DATAFRAMES INTO THE SQL DATABASE ---
print("\nLoading clean data maps into SQLite...")

# Extract foundational distinct AMFI dimensions to keep relational mapping happy
clean_nav = pd.read_csv("data/processed/nav_history_clean.csv")
unique_funds = pd.DataFrame({'amfi_code': clean_nav['amfi_code'].unique()})
unique_funds.to_sql("dim_fund", engine, if_exists="append", index=False)

# Convert datetimes to strings to map clean database tracking
clean_nav['date'] = clean_nav['date'].astype(str)
clean_nav.to_sql("fact_nav", engine, if_exists="append", index=False)

clean_tx = pd.read_csv("data/processed/investor_transactions_clean.csv")
clean_tx['transaction_date'] = clean_tx['transaction_date'].astype(str)
clean_tx.to_sql("fact_transactions", engine, if_exists="append", index=False)

clean_perf = pd.read_csv("data/processed/scheme_performance_clean.csv")
clean_perf.to_sql("fact_performance", engine, if_exists="append", index=False)

print("✓ Database generation complete! Created 'bluestock_mf.db'")

import pandas as pd

# Query top parameters via standard pandas SQL execution windows
query = """
SELECT
    f.amfi_code,
    p.return_3y,
    p.expense_ratio
FROM dim_fund f
JOIN fact_performance p ON f.amfi_code = p.amfi_code
ORDER BY p.return_3y DESC
LIMIT 5;
"""

df_results = pd.read_sql(query, engine)
print("=== TOP 5 FUNDS BY 3-YEAR RETURNS ===")
print(df_results)