# -*- coding: utf-8 -*-
"""Performance_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaTQw77wkFQDXmj6Z0HRgHXfm1T6ElQ8
"""

# ==========================================
# STEP 0: DEPENDENCY INSTALLATION & SETUPS
# ==========================================
# Install Yahoo Finance to fetch real benchmark indices
!pip install yfinance scipy pandas numpy matplotlib seaborn --quiet

import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from datetime import datetime, timedelta
import os

# Import Colab's specific file download library
from google.colab import files

# Create reports directory if it doesn't exist
os.makedirs('reports', exist_ok=True)

# ==========================================
# STEP 1: FETCH REAL LIVE BENCHMARK INDEX DATA
# ==========================================
print("Step 1: Fetching live Benchmark data from Yahoo Finance...")
end_date = datetime.now()
start_date = end_date - timedelta(days=5*365)

# Downloading Nifty 50 (^NSEI) and Nifty 500 (^NSEMDCP50) as a Nifty 100 proxy
benchmarks = yf.download(['^NSEI','^BSESN'], start=start_date, end=end_date)['Close']
benchmarks = benchmarks.fillna(method='ffill').dropna()
benchmarks.columns = ['nifty_50','nifty_100'] # Mapping names to your criteria template
benchmarks = benchmarks.reset_index()
benchmarks.rename(columns={'Date': 'date'}, inplace=True)

# Compute exact daily returns
benchmarks['nifty_50_ret'] = benchmarks['nifty_50'].pct_change()
benchmarks['nifty_100_ret'] = benchmarks['nifty_100'].pct_change()

# ==========================================
# STEP 2: SIMULATING 40 DIVERSIFIED SCHEMES
# ==========================================
print("Step 2: Synthesizing historical profiles for 40 schemes...")
np.random.seed(101) # Locked random seed for predictable replication

# Generate a master tracking roster containing 40 individual mutual funds
funds_master = []
fund_categories = ["Large Cap", "Mid Cap Growth", "Bluechip Alpha", "Tax Saver ELSS", "Dynamic Asset Allocator", "Focused Value", "Small Cap Edge", "Contra Fund Strategy"]

for i in range(1, 41):
    category = fund_categories[i % len(fund_categories)]
    funds_master.append({
        "amfi_code": 120000 + i,
        "scheme_name": f"Bluestock {category} Fund Series-{i}",
        "expense_ratio": round(np.random.uniform(0.0050, 0.0220), 4) # 0.5% to 2.2% limit spectrum
    })

nav_records = []
for fund in funds_master:
    current_nav = 10.0 if "Small Cap" in fund["scheme_name"] else 100.0
    beta = np.random.uniform(0.75, 1.30)
    idiosyncratic_vol = np.random.uniform(0.004, 0.014)

    for idx, row in benchmarks.iterrows():
        if idx == 0:
            nav_records.append({"amfi_code": fund["amfi_code"], "date": row["date"], "nav": current_nav})
            continue

        b_ret = row["nifty_100_ret"]
        # Capital Asset Pricing Model derivation + noise tracking error matrix minus annualized fees
        fund_ret = beta * b_ret + np.random.normal(0, idiosyncratic_vol) - (fund["expense_ratio"] / 252)
        current_nav *= (1 + fund_ret)
        nav_records.append({"amfi_code": fund["amfi_code"], "date": row["date"], "nav": current_nav})

df_nav = pd.DataFrame(nav_records)

# ==========================================
# STEP 3: FINANCIAL MATHEMATICS CODES ENGINE
# ==========================================
print("Step 3: Calculating Risk/Return parameters (Sharpe, Sortino, Alpha, Beta)...")
RF_ANNUAL = 0.065
RF_DAILY = RF_ANNUAL / 252

metrics_summary = []

for fund in funds_master:
    amfi = fund["amfi_code"]
    name = fund["scheme_name"]
    exp_ratio = fund["expense_ratio"]

    df_f = df_nav[df_nav['amfi_code'] == amfi].copy().sort_values('date')
    df_f['daily_return'] = df_f['nav'].pct_change()

    df_merged = pd.merge(df_f, benchmarks, on='date', how='inner').dropna()

    # CAGR computations
    latest_nav = df_f['nav'].iloc[-1]
    latest_date = df_f['date'].iloc[-1]

    cagr_dict = {}
    for years in [1, 3, 5]:
        target_date = latest_date - pd.DateOffset(years=years)
        historical_subset = df_f[df_f['date'] <= target_date]
        if not historical_subset.empty:
            start_nav = historical_subset['nav'].iloc[-1]
            actual_days = (latest_date - historical_subset['date'].iloc[-1]).days / 365.25
            cagr_dict[f'cagr_{years}yr'] = (latest_nav / start_nav) ** (1 / actual_days) - 1
        else:
            cagr_dict[f'cagr_{years}yr'] = np.nan

    # Sharpe and Sortino computation logic arrays
    fund_rets = df_merged['daily_return']
    mean_excess_ret = fund_rets.mean() - RF_DAILY
    std_ret = fund_rets.std()
    sharpe = (mean_excess_ret / std_ret) * np.sqrt(252) if std_ret > 0 else 0

    downside_rets = fund_rets[fund_rets < 0]
    downside_std = downside_rets.std() if len(downside_rets) > 1 else std_ret
    sortino = (mean_excess_ret / downside_std) * np.sqrt(252) if downside_std > 0 else 0

    # Alpha & Beta Ordinary Least Squares (OLS) via Scipy
    slope, intercept, r_value, p_value, std_err = stats.linregress(df_merged['nifty_100_ret'], fund_rets)
    beta_calc = slope
    alpha_calc = intercept * 252 # Annualized Alpha matrix

    # Tracking Maximum Peak-to-Trough Drawdowns
    df_f['running_max'] = df_f['nav'].cummax()
    df_f['drawdown'] = df_f['nav'] / df_f['running_max'] - 1
    max_dd = df_f['drawdown'].min()
    worst_dd_idx = df_f['drawdown'].idxmin()
    worst_date = df_f['date'].loc[worst_dd_idx]
    peak_date = df_f[df_f['date'] <= worst_date].sort_values('nav', ascending=False)['date'].iloc[0]

    # Tracking Error vs Nifty 50 Index Baseline
    tracking_error = np.std(fund_rets - df_merged['nifty_50_ret']) * np.sqrt(252)

    metrics_summary.append({
        'amfi_code': amfi, 'scheme_name': name, 'expense_ratio': exp_ratio,
        'cagr_1yr': cagr_dict['cagr_1yr'], 'cagr_3yr': cagr_dict['cagr_3yr'], 'cagr_5yr': cagr_dict['cagr_5yr'],
        'sharpe_ratio': sharpe, 'sortino_ratio': sortino, 'alpha': alpha_calc, 'beta': beta_calc,
        'max_drawdown': max_dd, 'worst_dd_start': peak_date.strftime('%Y-%m-%d'), 'worst_dd_end': worst_date.strftime('%Y-%m-%d'),
        'tracking_error': tracking_error
    })

df_metrics = pd.DataFrame(metrics_summary)

# ==========================================
# STEP 4: COMPOSITE PERFORMANCE SCORECARD
# ==========================================
print("Step 4: Compiling 0-100 composite rankings Matrix...")
df_metrics['rank_3yr'] = df_metrics['cagr_3yr'].rank(ascending=False)
df_metrics['rank_sharpe'] = df_metrics['sharpe_ratio'].rank(ascending=False)
df_metrics['rank_alpha'] = df_metrics['alpha'].rank(ascending=False)
df_metrics['rank_expense'] = df_metrics['expense_ratio'].rank(ascending=True) # Low fee rank is higher up
df_metrics['rank_max_dd'] = df_metrics['max_drawdown'].rank(ascending=False) # Safest DD profile rank is higher up

num_funds = len(df_metrics)
def get_score_component(rank_col):
    return (num_funds - rank_col + 1) / num_funds * 100

score_3yr = 0.30 * get_score_component(df_metrics['rank_3yr'])
score_sharpe = 0.25 * get_score_component(df_metrics['rank_sharpe'])
score_alpha = 0.20 * get_score_component(df_metrics['rank_alpha'])
score_expense = 0.15 * get_score_component(df_metrics['rank_expense'])
score_dd = 0.10 * get_score_component(df_metrics['rank_max_dd'])

df_metrics['fund_score'] = score_3yr + score_sharpe + score_alpha + score_expense + score_dd
df_metrics = df_metrics.sort_values('fund_score', ascending=False).reset_index(drop=True)

# Export structural CSV arrays
df_metrics[['amfi_code', 'scheme_name', 'alpha', 'beta']].to_csv('reports/alpha_beta.csv', index=False)
df_metrics.to_csv('reports/fund_scorecard.csv', index=False)

# ==========================================
# STEP 5: VISUAL GENERATOR PIPELINE
# ==========================================
print("Step 5: Visualizing asset profiles...")
plt.figure(figsize=(14, 7))
three_years_ago = datetime.now() - timedelta(days=3*365)
df_bench_3yr = benchmarks[benchmarks['date'] >= three_years_ago].copy()

plt.plot(df_bench_3yr['date'], (df_bench_3yr['nifty_50'] / df_bench_3yr['nifty_50'].iloc[0]) * 100, label='Nifty 50 Baseline', color='black', linewidth=2, linestyle='--')
plt.plot(df_bench_3yr['date'], (df_bench_3yr['nifty_100'] / df_bench_3yr['nifty_100'].iloc[0]) * 100, label='Nifty 100 Baseline', color='grey', linewidth=1.5, linestyle=':')

for amfi in df_metrics['amfi_code'].head(5):
    f_data = df_nav[(df_nav['amfi_code'] == amfi) & (df_nav['date'] >= three_years_ago)].sort_values('date')
    f_name = df_metrics[df_metrics['amfi_code'] == amfi]['scheme_name'].values[0]
    plt.plot(f_data['date'], (f_data['nav'] / f_data['nav'].iloc[0]) * 100, label=f_name, alpha=0.85)

plt.title('Top 5 Performing Funds vs Benchmark Baselines (3Y Normalized Wealth Cumulative Growth Chart)', fontsize=12, fontweight='bold')
plt.xlabel('Date Timeline')
plt.ylabel('Normalized Growth (Base 100 Index)')
plt.legend(loc='upper left', frameon=True)
plt.grid(True, alpha=0.3)
plt.savefig('reports/benchmark_comparison_chart.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nAll internal processes are complete! Initializing local browser asset file delivery downloads...")
# Trigger the download files from Colab's backend direct to your machine
files.download('reports/alpha_beta.csv')
files.download('reports/fund_scorecard.csv')
files.download('reports/benchmark_comparison_chart.png')